// This file has been generated by svg2code

function bugs_draw_000(c) // 'bug1'
{
    c.beginPath();
    c.moveTo(281.6, 340.3);
    c.lineTo(282.9, 338.7);
    c.lineTo(283.4, 337.0);
    c.lineTo(283.4, 338.9);
    c.lineTo(282.0, 340.8);
    c.closePath();
    c.fillStyle = 'rgb(0, 0, 0)';
    c.fill();
    c.beginPath();
    c.moveTo(283.2, 345.8);
    c.lineTo(285.2, 345.2);
    c.lineTo(286.5, 344.0);
    c.lineTo(285.5, 345.6);
    c.lineTo(283.3, 346.4);
    c.closePath();
    c.fill();
    c.beginPath();
    c.moveTo(282.3, 350.6);
    c.lineTo(283.4, 352.4);
    c.lineTo(284.8, 353.4);
    c.lineTo(283.0, 352.8);
    c.lineTo(281.7, 350.9);
    c.closePath();
    c.fill();
    c.beginPath();
    c.moveTo(273.4, 341.3);
    c.lineTo(271.8, 339.8);
    c.lineTo(271.2, 338.1);
    c.lineTo(271.2, 340.0);
    c.lineTo(272.8, 341.8);
    c.closePath();
    c.fill();
    c.beginPath();
    c.moveTo(272.4, 345.5);
    c.lineTo(270.0, 345.1);
    c.lineTo(268.4, 344.1);
    c.lineTo(269.5, 345.7);
    c.lineTo(272.1, 346.3);
    c.closePath();
    c.fill();
    c.beginPath();
    c.moveTo(272.7, 350.5);
    c.lineTo(271.2, 352.5);
    c.lineTo(269.6, 353.4);
    c.lineTo(271.4, 353.3);
    c.lineTo(273.2, 351.1);
    c.closePath();
    c.fill();
    c.beginPath();
    c.moveTo(277.7, 353.6);
    c.bezierCurveTo(269.9, 353.8, 268.9, 342.9, 274.3, 339.5);
    c.bezierCurveTo(275.9, 334.1, 279.8, 335.2, 281.0, 339.3);
    c.bezierCurveTo(287.1, 344.1, 285.4, 353.4, 277.7, 353.6);
    c.closePath();
    c.fill();
    c.beginPath();
    c.moveTo(280.6, 340.1);
    c.bezierCurveTo(286.9, 346.0, 282.1, 352.5, 277.9, 352.9);
    c.lineTo(277.8, 342.4);
    c.lineTo(278.7, 341.1);
    c.bezierCurveTo(279.2, 341.1, 279.9, 340.6, 280.6, 340.1);
    c.closePath();
    c.fillStyle = 'rgb(242, 26, 26)';
    c.fill();
    c.beginPath();
    c.moveTo(275.1, 340.3);
    c.bezierCurveTo(268.9, 344.3, 272.6, 352.9, 277.4, 352.9);
    c.lineTo(277.7, 342.4);
    c.lineTo(277.0, 341.2);
    c.bezierCurveTo(276.3, 341.1, 275.6, 340.8, 275.1, 340.3);
    c.closePath();
    c.fill();
    c.beginPath();
    c.moveTo(276.6, 336.9);
    c.bezierCurveTo(277.4, 337.7, 277.0, 338.3, 276.5, 338.6);
    c.bezierCurveTo(276.0, 338.9, 275.6, 338.0, 275.6, 338.0);
    c.bezierCurveTo(275.7, 337.6, 276.4, 337.0, 276.6, 336.9);
    c.closePath();
    c.fillStyle = 'rgb(255, 255, 255)';
    c.fill();
    c.beginPath();
    c.moveTo(278.8, 337.0);
    c.bezierCurveTo(277.9, 337.7, 278.4, 338.3, 278.9, 338.5);
    c.bezierCurveTo(279.4, 338.8, 279.8, 338.0, 279.8, 338.0);
    c.bezierCurveTo(279.7, 337.6, 279.0, 337.1, 278.8, 337.0);
    c.closePath();
    c.fill();
    c.beginPath();
    c.moveTo(279.7, 342.2);
    c.bezierCurveTo(279.9, 341.7, 280.8, 341.6, 281.2, 342.2);
    c.bezierCurveTo(281.6, 342.8, 281.0, 343.5, 280.4, 343.5);
    c.bezierCurveTo(279.7, 343.5, 279.4, 342.8, 279.7, 342.2);
    c.lineTo(279.7, 342.2);
    c.closePath();
    c.fillStyle = 'rgb(0, 0, 0)';
    c.fill();
    c.beginPath();
    c.moveTo(278.9, 345.6);
    c.bezierCurveTo(279.2, 345.0, 280.1, 344.9, 280.5, 345.5);
    c.bezierCurveTo(280.9, 346.1, 280.3, 346.8, 279.6, 346.8);
    c.bezierCurveTo(279.0, 346.8, 278.7, 346.1, 278.9, 345.6);
    c.lineTo(278.9, 345.6);
    c.closePath();
    c.fill();
    c.beginPath();
    c.moveTo(280.0, 348.9);
    c.bezierCurveTo(280.3, 348.3, 281.1, 348.3, 281.5, 348.8);
    c.bezierCurveTo(281.9, 349.4, 281.4, 350.1, 280.7, 350.1);
    c.bezierCurveTo(280.1, 350.1, 279.8, 349.5, 280.0, 348.9);
    c.lineTo(280.0, 348.9);
    c.closePath();
    c.fill();
    c.beginPath();
    c.moveTo(274.1, 342.9);
    c.bezierCurveTo(274.4, 342.3, 275.2, 342.3, 275.6, 342.8);
    c.bezierCurveTo(276.0, 343.4, 275.5, 344.1, 274.8, 344.1);
    c.bezierCurveTo(274.1, 344.1, 273.8, 343.5, 274.1, 342.9);
    c.lineTo(274.1, 342.9);
    c.closePath();
    c.fill();
    c.beginPath();
    c.moveTo(275.1, 345.7);
    c.bezierCurveTo(275.3, 345.2, 276.2, 345.1, 276.6, 345.7);
    c.bezierCurveTo(277.0, 346.3, 276.4, 347.0, 275.8, 347.0);
    c.bezierCurveTo(275.1, 347.0, 274.8, 346.3, 275.1, 345.7);
    c.lineTo(275.1, 345.7);
    c.closePath();
    c.fill();
    c.beginPath();
    c.moveTo(273.7, 348.8);
    c.bezierCurveTo(274.0, 348.2, 274.8, 348.1, 275.2, 348.7);
    c.bezierCurveTo(275.6, 349.3, 275.1, 350.0, 274.4, 350.0);
    c.bezierCurveTo(273.8, 350.0, 273.4, 349.3, 273.7, 348.8);
    c.lineTo(273.7, 348.8);
    c.closePath();
    c.fill();
}

var bugs_elements = {
    'bug1': { id: 'bug1', bounds: { x: 268.4, y: 335.8, width: 18.1, height: 17.8 }, drawfunction: bugs_draw_000 }
};

function bugs_draw(context, id, x, y, width, height)
{
    var element = bugs_elements[id];
    if (element !== undefined) {
        context.save();
        context.translate(x, y);
        if (width !== undefined && height !== undefined)
            context.scale(width / element.bounds.width, height / element.bounds.height);
        context.translate(-element.bounds.x, -element.bounds.y);
        element.drawfunction(context);
        context.restore();
    }
}

