// This file has been generated by svg2code

function grass_draw_000(c) // 'grass'
{
    c.beginPath();
    c.moveTo(46.9, 69.4);
    c.bezierCurveTo(47.3, 132.2, 43.7, 223.2, 49.3, 270.5);
    c.bezierCurveTo(55.9, 153.0, 68.5, 97.6, 76.9, 36.6);
    c.bezierCurveTo(72.5, 118.1, 61.7, 236.0, 68.6, 283.7);
    c.bezierCurveTo(72.4, 179.5, 84.8, 147.0, 94.7, 92.9);
    c.bezierCurveTo(91.7, 159.4, 84.4, 227.6, 88.6, 263.2);
    c.bezierCurveTo(94.7, 172.2, 100.4, 110.6, 109.4, 46.9);
    c.bezierCurveTo(107.6, 117.7, 104.9, 205.8, 108.6, 260.0);
    c.bezierCurveTo(112.7, 178.8, 123.6, 118.0, 131.5, 73.7);
    c.bezierCurveTo(127.1, 148.7, 124.9, 220.9, 130.7, 278.8);
    c.bezierCurveTo(130.7, 190.9, 138.2, 125.9, 147.6, 66.1);
    c.bezierCurveTo(142.9, 141.6, 141.2, 226.0, 147.9, 273.9);
    c.bezierCurveTo(152.0, 173.9, 160.4, 119.1, 172.9, 61.5);
    c.bezierCurveTo(166.2, 209.3, 158.1, 357.6, 166.4, 427.5);
    c.lineTo(33.6, 427.5);
    c.bezierCurveTo(31.2, 328.6, 29.6, 175.2, 46.9, 69.4);
    c.closePath();
    c.fillStyle = 'rgb(0, 128, 0)';
    c.fill();
    c.beginPath();
    c.moveTo(45.5, 95.1);
    c.bezierCurveTo(41.0, 164.9, 41.3, 272.1, 50.1, 323.4);
    c.bezierCurveTo(53.8, 200.2, 65.4, 124.8, 73.8, 63.9);
    c.bezierCurveTo(66.9, 146.2, 56.1, 264.7, 69.4, 325.4);
    c.bezierCurveTo(75.0, 238.0, 79.5, 180.5, 91.9, 115.8);
    c.bezierCurveTo(82.5, 201.9, 83.1, 282.0, 87.3, 317.6);
    c.bezierCurveTo(96.2, 236.4, 99.6, 140.3, 106.8, 76.3);
    c.bezierCurveTo(105.0, 147.1, 101.1, 245.0, 109.0, 323.0);
    c.bezierCurveTo(111.8, 252.4, 121.2, 142.6, 129.2, 98.3);
    c.bezierCurveTo(120.5, 193.0, 124.7, 276.9, 133.3, 324.2);
    c.bezierCurveTo(133.3, 236.3, 134.8, 157.1, 144.2, 97.4);
    c.bezierCurveTo(139.6, 172.8, 139.5, 265.1, 149.7, 324.5);
    c.bezierCurveTo(152.7, 215.2, 157.0, 146.9, 169.9, 81.6);
    c.bezierCurveTo(160.0, 222.1, 160.4, 370.3, 169.4, 428.9);
    c.lineTo(30.8, 428.9);
    c.bezierCurveTo(29.2, 347.1, 37.6, 171.7, 45.5, 95.1);
    c.closePath();
    c.fillStyle = 'rgb(0, 255, 0)';
    c.fill();
}

var grass_elements = {
    'grass': { id: 'grass', bounds: { x: 30.6, y: 36.6, width: 142.3, height: 392.3 }, drawfunction: grass_draw_000 }
};

function grass_draw(context, id, x, y, width, height)
{
    var element = grass_elements[id];
    if (element !== undefined) {
        context.save();
        context.translate(x, y);
        if (width !== undefined && height !== undefined)
            context.scale(width / element.bounds.width, height / element.bounds.height);
        context.translate(-element.bounds.x, -element.bounds.y);
        element.drawfunction(context);
        context.restore();
    }
}

